site_name: BioSFGroup
site_description: >-
  The present research work in Biomolecular Structure and Function Group is
  centered on DNA methylation and Alzheimer's disease.
site_author: Željko Svedružić
site_url: https://svedruziclab.github.io/
use_directory_urls: false
copyright: >-
  Copyright &copy; 2015 - 2023 Željko Svedružić. All rights reserved.
  <a href="#__consent">Change cookie settings</a>.
repo_url: https://github.com/svedruziclab/svedruziclab.github.io/
edit_uri: blob/main/docs/
nav:
  - Introduction: index.md
  - News:
      - news/index.md
  - PI: principal-investigator.md
  - Group: group.md
  - Research: research.md
  - Software: software.md
  - Teaching: teaching.md
  - Contact: contact.md
theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
extra:
  analytics:
    provider: google
    property: G-Z6K7QSCHCE
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zeljkosvedruzic
      name: Željko Svedružić on LinkedIn
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Zeljko_Svedruzic
      name: Željko Svedružić on ResearchGate
    - icon: fontawesome/brands/github
      link: https://github.com/svedruziclab
      name: BioSFGroup on GitHub
plugins:
  - blog:
      blog_dir: news
  - search
  - social
  - tags
