authors:
  zsvedruzic:
    name: Željko Svedružić
    description: Principal Investigator
    avatar: https://github.com/zsvedruzic.png
    url: https://hr.wikipedia.org/wiki/%C5%BDeljko_Svedru%C5%BEi%C4%87
  randretic:
    name: Rozi Andretić Waldowski
    description: Associate Professor at Department of Biotechnology
    avatar: https://github.com/github.png
    url: https://andreticlab.wordpress.com/
  lzoldos:
    name: Lana Žoldoš
    description: Podcast Host at Kišobran
    avatar: https://github.com/github.png
    url: https://kisobran.uniri.hr/tag/lana-zoldos/
  careynolds:
    name: Christian Andrew Reynolds
    description: Assistant Professor at Department of Biotechnology
    avatar: https://github.com/github.png
    url: https://portal.uniri.hr/Portfelj/index/4224
