authors:
  zsvedruzic:
    name: Željko Svedružić
    description: Principal Investigator
    avatar: https://github.com/zsvedruzic.png
    url: https://hr.wikipedia.org/wiki/%C5%BDeljko_Svedru%C5%BEi%C4%87
